### ISSUE TITLE
Cannot close settings.

### ISSUE THREAD

**Issue by emmanuelmahove** [kimlimjustin/xplorer#106] opened 2021-09-30 14:57 UTC
**Describe the bug**
Xplorer gets stuck when you go to settings.

**To Reproduce**
1. Go to Settings
2. Click on "⬆️ Settings" to close settings
4. Nothing happens

**Expected behavior**
When "⬆️ Settings" is clicked the app should close settings.

**Screenshots**
![Screenshot 2021-09-30 165303](https://user-images.githubusercontent.com/59018510/135479120-7cea0d4c-56d6-44f3-a67d-344c2a1ff4ee.png)

**Desktop (please complete the following information):**
- OS Version: Windows 11 Pro 21H2 22000.194
- App Version: v0.1.0

**Additional comment**

**Comment by kimlimjustin** [comment] 2021-09-30 15:00
Duplicate of #61 and being implemented on #63, merged into master

If you want to get the latest version, you can try build from source :)

Thanks!

**Closed by kimlimjustin** 2021-09-30 15:00 UTC
Labels: bug
