### ISSUE TITLE
Unable to open Desktop folder

### ISSUE THREAD

**Issue by Ponokefalos** [kimlimjustin/xplorer#60] opened 2021-09-26 15:34 UTC
**Describe the bug**
App crashes when I try to navigate to Desktop (windows) folder.

**To Reproduce**
1. Just open Desktop

**Expected behavior**
Show the desktop files and folders

**Screenshots**
Heres a video
https://user-images.githubusercontent.com/5969566/134814312-f79f3b9b-fdf7-44d1-bdd3-6f83fcb775ab.mp4

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1909 18363.1316]
 - App Version: 0.1.0

**Additional comment**
The only thing I  was able to think is that in my Desktop folder I have some files/folders with name that consist of Greek characters. Not sure if this rings any bels

**Comment by kimlimjustin** [comment] 2021-09-26 15:37
Thanks for the report, will look into it tomorrow (it's too late to me haha)

**Comment by rushabh-wadkar** [comment] 2021-09-26 18:53
I tried to reproduce this on my system. It's working on Linux. I also tried with folders & files with names consisting of Greek characters. It doesn't seem to have any issue with that.

**Comment by kimlimjustin** [comment] 2021-09-27 00:15
Do you use OneDrive? This may be an error caused because you got OneDrive with it and Microsoft store your desktop files in the onedrive instead of the local drive, OneDrive is not supported yet on 0.1.0. Will surely add it soon!

**Comment by 4lenz1** [comment] 2021-09-27 02:57
I can navigate to Desktop without problem, 
but app crashes when I  navigate to Downloads

**Comment by kimlimjustin** [comment] 2021-09-27 03:23
> In my situation, I can navigate to Desktop without problem,
> but app crashes when I navigate to Downloads

Same question, do you use OneDrive? Thanks

**Comment by Ponokefalos** [comment] 2021-09-27 07:51
> Do you use OneDrive? This may be an error caused because you got OneDrive with it and Microsoft store your desktop files in the onedrive instead of the local drive, OneDrive is not supported yet on 0.1.0. Will surely add it soon!

Yes I use One Drive. Strange thing is that after many tests I got the app to open my Desktop folder but I dont know why!

**Comment by kimlimjustin** [comment] 2021-09-27 07:54
> after many tests I got the app to open my Desktop folder

Is it okay with the files?

**Comment by Ponokefalos** [comment] 2021-09-27 08:08
> Is it okay with the files?

Yes files are ok. Now I have just downloaded the app on different windows laptop 
`Windows: 10.0.19042 Build 19042`
without one Drive and I cannot open the Downloads folder as @4lenz1 mentioned above

**Comment by kimlimjustin** [comment] 2021-09-27 08:13
> > Is it okay with the files?
> 
> Yes files are ok. Now I have just downloaded the app on different windows laptop
> `Windows: 10.0.19042 Build 19042`
> without one Drive and I cannot open the Downloads folder as @4lenz1 mentioned above

Could you please type `Ctrl + Shift + I` to open the devtool and navigate into the `Console` section (just like chrome devtool) and share the error?

**Comment by Ponokefalos** [comment] 2021-09-27 08:16
>Could you please type Ctrl + Shift + I to open the devtool and navigate into the Console section (just like chrome devtool) and share the error?

Yes I got this
![disc](https://user-images.githubusercontent.com/5969566/134870415-021419f4-c652-4169-904c-d7f165504994.PNG)
Seems like the app crashes

**Comment by kimlimjustin** [comment] 2021-09-27 08:19
Does restart windows fix it?

**Comment by Ponokefalos** [comment] 2021-09-27 08:21
>Does restart windows fix it?
I have some strange files inside `Downloads` . Files with extension .exe, .config, .msi, .patch, .ovpn. I will check if one of them causing the issue and the I will try the restart!

**Comment by Ponokefalos** [comment] 2021-09-27 08:26
Great news! Its .exe files. If I remove it from `Downloads` folder it opens correctly. I replicate the issue on `Desktop` folder and it has the same behavior too.

**Comment by kimlimjustin** [comment] 2021-09-27 08:27
Ah, saying about exe, it might because it too, please open setting and disable `Extract exe file icon and make it as preview`, does it works?

**Comment by Ponokefalos** [comment] 2021-09-27 08:32
> please open setting and disable Extract exe file icon and make it as preview

Yes you were right, I disabled the setting and now it works!

**Comment by kimlimjustin** [comment] 2021-09-27 08:34
> > please open setting and disable `Extract exe file icon and make it as preview`
> 
> Yes you were right, I disabled the setting and now it works!

WOW, TYSM for pointing it out, will write it into documentation. Closing this issue for now.....

**Closed by kimlimjustin** 2021-09-27 08:34 UTC
Labels: bug
