### ISSUE TITLE
settings toggle button, clickable area

### ISSUE THREAD

**Issue by AmirhoseinHesami** [kimlimjustin/xplorer#94] opened 2021-09-28 16:43 UTC
**Problem**
The problem is that the _clickable area_ for the _settings toggle button_ is really small and the user should exactly click on the arrow to toggle the settings and it's painful. 
initially, I thought that maybe it was a bug however I've realized that I have to exactly click on the arrow to toggle the settings as I go through docs.

**Solution**
I think it's a good idea to expand the clickable area to both the **"Settings" text and the arrow** for a bigger clickable area.
in my view, it would affect a better UX in general.

**Alternative**
Another solution would be to expand the clickable area to the whole section at the top left corner.

**The proposed Clickable Area:** [https://drive.google.com/file/d/1kYmX0_-_ooLne7GvvFMXLzBfiJETYk_G/view?usp=sharing]()

I appreciate what you've done, It's a great project, I really like it, thumbs up.

**Comment by kimlimjustin** [comment] 2021-09-29 00:12
Duplicate of #61 and being implemented on #63, merged  into master

If you want to get the latest version, you can try build from source :)

Thanks!

**Closed by kimlimjustin** 2021-09-29 00:12 UTC
Labels: enhancement
