### ISSUE TITLE
Windows: Layout mode - Cannot select view when hover mouse

### ISSUE THREAD

**Issue by phamthanhtuan100mc** [kimlimjustin/xplorer#163] opened 2021-10-17 03:14 UTC
### Description

Cannot select view mode (For example Grid view, Detail view) in the context menu when perform right-click.
I'm using this version of Windows 10:
==========================================
Edition	Windows 10 Pro
Version	21H1
Installed on	‎6/‎9/‎2021
OS build	19043.1288
Experience	Windows Feature Experience Pack 120.2212.3920.0
==========================================

### Steps To Reproduce

1. Go to any folder that contains files
2. Perform right-click in the clear area (not right-click in the file or folder)\
3. Hover mouse to "Layout mode" section
4. Hover to the sub-context menu that appears on the right and moves to "Detail View"

Here is the video demo:
https://user-images.githubusercontent.com/30611848/137609390-dc1e787e-a390-4fce-96c2-d4b10b16940b.MP4

### Expected behavior

The sub-context menu that appears on the right will appear and I suppose to be able to choose the View Setting that I wanted

### Xplorer Version

v0.1.0

### Operating System Version

Windows 10 21H1

**Comment by kimlimjustin** [comment] 2021-10-17 12:07
Duplicate of #48, fixed via #154 on `master` branch, stay tuned for next release!

**Closed by kimlimjustin** 2021-10-17 12:07 UTC
Labels: bug
