### ISSUE TITLE
disorderly code in name of drives

### ISSUE THREAD

**Issue by LPYTY** [kimlimjustin/xplorer#164] opened 2021-10-17 07:50 UTC
### Description

disorderly code in the name of drives(the disks don't have a name)

### Steps To Reproduce

Windows 10 21H1 x64
Chinese Simplified
the two drives don't have names

### Expected behavior

should show “本地磁盘（C:）” and “本地磁盘（D:）”

### Xplorer Version

v0.1.0

### Operating System Version

Windows 10 21H1 x64

### Additional Information

![屏幕截图 2021-10-17 154057](https://user-images.githubusercontent.com/61695629/137617378-150b3bee-4ef8-4cc5-833e-ab38950b8f56.jpg)

**Comment by kimlimjustin** [comment] 2021-10-17 12:15
Duplicate of #114, resolved via #144 (here's a night build, https://drive.google.com/file/d/1uZNJg6GLKfYEBcxR9rLWVbUGUxYatMlf/view?usp=sharing)

**Closed by kimlimjustin** 2021-10-17 12:15 UTC
Labels: bug
